In [1]:
import numpy as np

In [2]:
zero_array=np.zeros((10),dtype=np.int8)

In [3]:
zero_array.dtype

dtype('int8')

In [4]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [5]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [6]:
np.empty(5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [7]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [19]:
np.ones([2,2], dtype=np.int)

<ipython-input-19-b2fe104d15dd>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones([2,2], dtype=np.int)


array([[1, 1],
       [1, 1]])

In [13]:
a=np.array(1,dtype=np.int64)

In [14]:
a

array(1)

In [21]:
a=np.ones([3,2], dtype=np.float)

<ipython-input-21-0f677e36eade>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a=np.ones([3,2], dtype=np.float)


In [22]:
a

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
a.shape

(3, 2)

In [31]:
b=np.ones(a.shape,dtype=a.dtype)

In [32]:
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [29]:
b.dtype

dtype('int64')

In [30]:
a.dtype

dtype('float64')

In [34]:
b=np.ones_like(a)
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [35]:
b=np.zeros_like(a)
b

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [38]:
b=np.full(shape=[4,4],fill_value=5, dtype=np.int)
b

<ipython-input-38-8a2bd5dc553b>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  b=np.full(shape=[4,4],fill_value=5, dtype=np.int)


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [39]:
b=np.ones(shape=[4,4],dtype=np.int)*5
b

<ipython-input-39-b7f70bf77673>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  b=np.ones(shape=[4,4],dtype=np.int)*5


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [40]:
c=np.ones_like(b)*7
c

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [44]:
c=np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
c=np.random.randint(low=2, high=10)
c

9

In [50]:
c=np.random.randint(10,size=3)
c

array([5, 4, 4])

In [52]:
c=np.random.random(size=[3,3,3])
c

array([[[0.86924111, 0.52840729, 0.10128654],
        [0.90832885, 0.88210314, 0.34316807],
        [0.59878527, 0.27907059, 0.32184563]],

       [[0.08618431, 0.63792627, 0.51466879],
        [0.4141053 , 0.18714623, 0.85907186],
        [0.48381953, 0.56333966, 0.57784149]],

       [[0.77915105, 0.11725603, 0.02882226],
        [0.98818089, 0.68095891, 0.58032847],
        [0.51915207, 0.76804695, 0.52135054]]])

In [2]:
lst=[1,2,3,4,5]
len(lst)

5

In [7]:
numpy_lst=np.asarray(lst)
numpy_lst

array([1, 2, 3, 4, 5])

In [4]:
type(lst)

list

In [5]:
type(numpy_lst)

numpy.ndarray

In [6]:
id(numpy_lst)

136021039531760

In [8]:
y=np.copy(numpy_lst)

In [9]:
y

array([1, 2, 3, 4, 5])

In [10]:
id(y)

136020626886064

In [11]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
y=np.linspace(1,9,5,dtype=np.int)
y

<ipython-input-17-cd79cffadeaa>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y=np.linspace(1,9,5,dtype=np.int)


array([1, 3, 5, 7, 9])

In [19]:
y=np.arange(1,11,2)
y

array([1, 3, 5, 7, 9])

In [23]:
y=np.arange(10,0,-1)
y

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [25]:
z=np.arange(9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
z.nbytes

72

In [27]:
z[0].itemsize

8

In [34]:
print("%d bytes" % (z.size * z.itemsize))

72 bytes


In [29]:
z.size

9

In [30]:
z.itemsize

8

In [3]:
x=np.arange(1,5)
x[0]

1

In [5]:
x[x.size-1]

4

In [6]:
x[-1]

4

In [8]:
x[0:3]

array([1, 2, 3])

In [9]:
x[1:-1]

array([2, 3])

In [11]:
y=np.flip(x)
y

array([4, 3, 2, 1])

In [22]:
x[::-1]

array([4, 3, 2, 1])

In [23]:
x[::2]

array([1, 3])

In [27]:
z[0]

array([0, 1, 2])

In [28]:
z.size

9

In [29]:
z.nrows

AttributeError: ignored

In [30]:
z.shape

(3, 3)

In [32]:
z[z.shape[0]-1]

array([6, 7, 8])

In [33]:
z[-1]

array([6, 7, 8])

In [34]:
z[0,0]

0

In [35]:
z[-1,-1]

8

In [36]:
z[1:-1]

array([[3, 4, 5]])

In [38]:
z[:2,:2]

array([[0, 1],
       [3, 4]])

In [40]:
z[-2:,-2:]

array([[4, 5],
       [7, 8]])

In [41]:
x

array([1, 2, 3, 4])

In [44]:
x_float=np.array(x,np.float)
x_float

<ipython-input-44-168a405ebae7>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x_float=np.array(x,np.float)


array([1., 2., 3., 4.])

In [45]:
np.sort(x)

array([1, 2, 3, 4])

In [46]:
x=np.arange(0,8)

In [47]:
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [48]:
x[4]=1

In [49]:
x

array([0, 1, 2, 3, 1, 5, 6, 7])

In [50]:
x[4]=50

In [51]:
x

array([ 0,  1,  2,  3, 50,  5,  6,  7])

In [55]:
np.where(x!=50,x,40)

array([ 0,  1,  2,  3, 40,  5,  6,  7])

In [56]:
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [57]:
z[-1]=1

In [58]:
z

array([[0, 1, 2],
       [3, 4, 5],
       [1, 1, 1]])

In [59]:
z[-1,-1]=0
z

array([[0, 1, 2],
       [3, 4, 5],
       [1, 1, 0]])

In [60]:
z+=5
z

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [ 6,  6,  5]])