<a href="https://colab.research.google.com/github/roldugina/data_analysis_projects/blob/main/FreeCodeCamp_2_nparrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
zero_array=np.zeros((10),dtype=np.int8)

In [ ]:
zero_array.dtype

dtype('int8')

In [ ]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [ ]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [ ]:
np.empty(5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
np.ones([2,2], dtype=np.int)

<ipython-input-19-b2fe104d15dd>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones([2,2], dtype=np.int)


array([[1, 1],
       [1, 1]])

In [ ]:
a=np.array(1,dtype=np.int64)

In [ ]:
a

array(1)

In [ ]:
a=np.ones([3,2], dtype=np.float)

<ipython-input-21-0f677e36eade>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a=np.ones([3,2], dtype=np.float)


In [ ]:
a

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
a.shape

(3, 2)

In [ ]:
b=np.ones(a.shape,dtype=a.dtype)

In [ ]:
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
b.dtype

dtype('int64')

In [ ]:
a.dtype

dtype('float64')

In [ ]:
b=np.ones_like(a)
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
b=np.zeros_like(a)
b

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
b=np.full(shape=[4,4],fill_value=5, dtype=np.int)
b

<ipython-input-38-8a2bd5dc553b>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  b=np.full(shape=[4,4],fill_value=5, dtype=np.int)


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:
b=np.ones(shape=[4,4],dtype=np.int)*5
b

<ipython-input-39-b7f70bf77673>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  b=np.ones(shape=[4,4],dtype=np.int)*5


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:
c=np.ones_like(b)*7
c

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [ ]:
c=np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
c=np.random.randint(low=2, high=10)
c

9

In [ ]:
c=np.random.randint(10,size=3)
c

array([5, 4, 4])

In [ ]:
c=np.random.random(size=[3,3,3])
c

array([[[0.86924111, 0.52840729, 0.10128654],
        [0.90832885, 0.88210314, 0.34316807],
        [0.59878527, 0.27907059, 0.32184563]],

       [[0.08618431, 0.63792627, 0.51466879],
        [0.4141053 , 0.18714623, 0.85907186],
        [0.48381953, 0.56333966, 0.57784149]],

       [[0.77915105, 0.11725603, 0.02882226],
        [0.98818089, 0.68095891, 0.58032847],
        [0.51915207, 0.76804695, 0.52135054]]])

In [ ]:
lst=[1,2,3,4,5]
len(lst)

5

In [ ]:
numpy_lst=np.asarray(lst)
numpy_lst

array([1, 2, 3, 4, 5])

In [ ]:
type(lst)

list

In [ ]:
type(numpy_lst)

numpy.ndarray

In [ ]:
id(numpy_lst)

136021039531760

In [ ]:
y=np.copy(numpy_lst)

In [ ]:
y

array([1, 2, 3, 4, 5])

In [ ]:
id(y)

136020626886064

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
y=np.linspace(1,9,5,dtype=np.int)
y

<ipython-input-17-cd79cffadeaa>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y=np.linspace(1,9,5,dtype=np.int)


array([1, 3, 5, 7, 9])

In [ ]:
y=np.arange(1,11,2)
y

array([1, 3, 5, 7, 9])

In [ ]:
y=np.arange(10,0,-1)
y

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
z=np.arange(9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
z.nbytes

72

In [ ]:
z[0].itemsize

8

In [ ]:
print("%d bytes" % (z.size * z.itemsize))

72 bytes


In [ ]:
z.size

9

In [ ]:
z.itemsize

8

In [ ]:
x=np.arange(1,5)
x[0]

1

In [ ]:
x[x.size-1]

4

In [ ]:
x[-1]

4

In [ ]:
x[0:3]

array([1, 2, 3])

In [ ]:
x[1:-1]

array([2, 3])

In [ ]:
y=np.flip(x)
y

array([4, 3, 2, 1])

In [ ]:
x[::-1]

array([4, 3, 2, 1])

In [ ]:
x[::2]

array([1, 3])

In [ ]:
z[0]

array([0, 1, 2])

In [ ]:
z.size

9

In [ ]:
z.nrows

AttributeError: ignored

In [ ]:
z.shape

(3, 3)

In [ ]:
z[z.shape[0]-1]

array([6, 7, 8])

In [ ]:
z[-1]

array([6, 7, 8])

In [ ]:
z[0,0]

0

In [ ]:
z[-1,-1]

8

In [ ]:
z[1:-1]

array([[3, 4, 5]])

In [ ]:
z[:2,:2]

array([[0, 1],
       [3, 4]])

In [ ]:
z[-2:,-2:]

array([[4, 5],
       [7, 8]])

In [ ]:
x

array([1, 2, 3, 4])

In [ ]:
x_float=np.array(x,np.float)
x_float

<ipython-input-44-168a405ebae7>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x_float=np.array(x,np.float)


array([1., 2., 3., 4.])

In [ ]:
np.sort(x)

array([1, 2, 3, 4])

In [ ]:
x=np.arange(0,8)

In [ ]:
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
x[4]=1

In [ ]:
x

array([0, 1, 2, 3, 1, 5, 6, 7])

In [ ]:
x[4]=50

In [ ]:
x

array([ 0,  1,  2,  3, 50,  5,  6,  7])

In [ ]:
np.where(x!=50,x,40)

array([ 0,  1,  2,  3, 40,  5,  6,  7])

In [ ]:
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
z[-1]=1

In [ ]:
z

array([[0, 1, 2],
       [3, 4, 5],
       [1, 1, 1]])

In [ ]:
z[-1,-1]=0
z

array([[0, 1, 2],
       [3, 4, 5],
       [1, 1, 0]])

In [ ]:
z+=5
z

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [ 6,  6,  5]])

In [3]:
x=[1,2,3]
print(x,type(x))

[1, 2, 3] <class 'list'>


In [7]:
y=np.array(x)
print(y,type(y))

[1 2 3] <class 'numpy.ndarray'>


In [9]:
print(x,id(x))

[1, 2, 3] 139148808529984


In [12]:
x=np.array([1,2,3])
print(x,type(x),id(x))

[1 2 3] <class 'numpy.ndarray'> 139148195840336


In [14]:
y=x
print(y,type(y),id(y))

[1 2 3] <class 'numpy.ndarray'> 139148195840336


In [15]:
y=np.copy(x)
print(y,type(y),id(y))

[1 2 3] <class 'numpy.ndarray'> 139148195447024


In [18]:
arr=np.arange(1,11)
print(arr,type(arr))

[ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'>


In [19]:
arr=np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [21]:
arr=np.arange(10,0,-1)
arr

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [33]:
arr2=np.arange(1,11)
arr2[0:9:-2]

array([], dtype=int64)

In [34]:
matr=np.arange(0,9).reshape(3,3)
matr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
number=matr.size*matr.itemsize
number

72

In [38]:
matr.itemsize

8

In [40]:
np.identity(3, 3)



TypeError: ignored

In [6]:
x=np.arange(1,10)

In [43]:
x[0]

1

In [44]:
x[-1]

9

In [46]:
x[:3]

array([1, 2, 3])

In [47]:
x[1:-1]

array([2, 3, 4, 5, 6, 7, 8])

In [5]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [6]:
x[::2]

array([1, 3, 5, 7, 9])

In [7]:
y=x.reshape(3,3)

In [8]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
y[0]

array([1, 2, 3])

In [10]:
y[-1]

array([7, 8, 9])

In [11]:
y[0,0]

1

In [12]:
y[-1,-1]

9

In [13]:
y[1:-1,1:-1]

array([[5]])

In [14]:
y[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [15]:
y[-2:,-2:]

array([[5, 6],
       [8, 9]])

In [16]:
x.dtype

dtype('int64')

In [17]:
x.dtype=np.float16

In [18]:
x.dtype

dtype('float16')

In [4]:
x=np.array(x,float)
x

NameError: ignored

In [2]:
x

NameError: ignored

In [24]:
x=np.arange(1,10)

In [25]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
%time x=x[::-1]

CPU times: user 15 µs, sys: 0 ns, total: 15 µs
Wall time: 18.4 µs


In [30]:
%time x=np.flip(x)

CPU times: user 37 µs, sys: 4 µs, total: 41 µs
Wall time: 44.3 µs


In [31]:
x.sort

<function ndarray.sort>

In [32]:
x

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [33]:
x=np.sort(x)

In [34]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
x.sort()

In [36]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
x[4]=1
x

array([1, 2, 3, 4, 1, 6, 7, 8, 9])

In [39]:
x[x==1]=4
x

array([4, 2, 3, 4, 4, 6, 7, 8, 9])

In [40]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
y[-1]=1
y

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [43]:
y[-1,-1]=0
y

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 0]])

In [44]:
y=y+5
y

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [ 6,  6,  5]])

In [47]:
y+=5
y

array([[21, 22, 23],
       [24, 25, 26],
       [21, 21, 20]])

In [48]:
y+=5
y

array([[26, 27, 28],
       [29, 30, 31],
       [26, 26, 25]])

In [49]:
x[0]=-1
x[3]=-3
x[x<0]

array([-1, -3])

In [50]:
mask=x<0
mask

array([ True, False, False,  True, False, False, False, False, False])

In [51]:
x[mask]

array([-1, -3])

In [52]:
mask=x>5
x[mask]

array([6, 7, 8, 9])

In [54]:
x[x>x.mean()]

array([4, 6, 7, 8, 9])

In [8]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
mask=(x==2)|(x==10)
x[mask]

array([2])

In [20]:
%time all(x!=0)

CPU times: user 45 µs, sys: 4 µs, total: 49 µs
Wall time: 53.9 µs


True

In [23]:
%time zero=x!=0
zero.all()

CPU times: user 37 µs, sys: 3 µs, total: 40 µs
Wall time: 42.7 µs


True

In [29]:
%time zero=x==0
zero

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 7.87 µs


True

In [30]:
x

0

In [2]:
x=np.arange(1,10)
zero=x==0
np.any(zero)

False

In [37]:
sum(x)

45

In [39]:
x.sum()

45

In [40]:
x.mean()

5.0

In [4]:
y=x.reshape(3,3)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
y.mean()

5.0

In [3]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
y.sum(0,initial=1)

array([13, 16, 19])

In [6]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
y.sum(0)

array([12, 15, 18])

In [8]:
y.sum(0,where=y>5)

array([ 7,  8, 15])

In [9]:
y.mean(1)

array([2., 5., 8.])

In [10]:
x.max()

9